#!/bin/sh

nm="Dedup"
vs="r1"
dedupversion="""
        \e[1;42m $nm \e[0m\e[100m version $vs \e[0m
        De-duplicate files and keep organized on a common place (while copying them as symlinks) and create opposite versions from the same file.
        \e[100m Created in 11-14-2019 by Daniell Mesquita \e[0m
"""

if [ "$1" = "" ]; then
   echo "$dedupversion"
   echo "Type 'dedup --help' (without quotes) to see a list of available commands."
fi

# displays help message with a list of commands:
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
   echo "        \e[1;42m $nm $vs \e[0m"
   echo "Use these commands after/together with 'dedup' command."
   echo "Available commands:"
   echo "Information:"
   echo "  --help, -h                          Shows all available commands"
   echo "  --version, -v                       Shows the version of $nm"
   echo "  file <file/folder> <category>       De-duplicate a file/folder by name to a category"
   echo "  file <file/folder>                  De-duplicate a file/folder by name without any category"
   echo "  new-category <name>                 Creates a new category"
#   echo "  move-file <file/folder> <category>  Moves a uncategorized file/folder to a category"
   echo "  place <name>                        Creates a 'copy' (symlink) of a uncategorized de-dupliced file"
   echo "  place -c <category> <name>          Creates a 'copy' of a categorized de-dupliced file (can also use --with-category flag)"
   echo "----------------------------------------------------------"
   echo "Please note you can't change the origin files, or its symlinks will not work. So, be careful when choosing a category for a de-dupliced file."
fi

if [ "$1" = "new-category" ]; then
   mkdir /1/libraries/replic/.category/$2 && mkdir /1/libraries/replic/.category/$2/.oppose
   echo "Created category '$2'."
fi

if [ "$1" = "file" ]; then
   if [ "$3" != "" ]
      then
         if [ ! -e /1/libraries/replic/.category/$3 ]; then
            echo "Category '$3' doesn't exist; but as a nice program, I'll create it for you."
            dedup new-category $3
fi
         mv $2 /1/libraries/replic/.category/$3
         ln -s /1/libraries/replic/.category/$3/$2
         echo "De-dupliced '$2' in category '$3'."
      else
         mv $2 /1/libraries/replic
         ln -s /1/libraries/replic/$2
         echo "De-dupliced '$2'. It's so magic! But please note it won't work on filesystems which doesn't supports symbolic links."
fi
fi

if [ "$1" = "place" ]; then
   if [ "$2" = "-c" ] || [ "$1" = "--with-category" ]
      then
         ln -s /1/libraries/replic/.category/$3/$4 .
      else
         ln -s /1/libraries/replic/$2 .
fi
   echo "Please note it won't work on filesystems which doesn't supports symbolic links."
fi

#if [ "$1" = "move-file" ]; then
#   if [ ! -e /1/libraries/replic/.category/$3 ]
#      then
#         echo "Category '$3' doesn't exist; but as a nice program, I'll create it for you."
#         dedup new-category $3
#fi
#   mv /1/libraries/replic/$2 /1/libraries/replic/.category/$3
#   echo "File '$2' now haves a category, and it is '$3'!"
#fi

if [ "$1" = "--version" ] || [ "$1" = "-v" ]; then
   echo "$dedupversion"
fi
